DROP TABLE IF EXISTS course_enrollment;

CREATE TABLE course_enrollment(
    enrollment_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    enrollment_student_id INT,
    enrollment_course_id INT,
    enrollment_start_date DATE,
    enrollment_end_date DATE,
    enrollment_date DATE
);