DROP TABLE IF EXISTS courses;

CREATE TABLE courses(
    course_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    course_name VARCHAR(100),
    course_capacity INT,
    course_teacher INT
);