DROP TABLE IF EXISTS students;

CREATE TABLE students(
    student_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    ed_year INT,
    date_of_birth DATE,
    email VARCHAR(100),
    gender VARCHAR(6)
);