DROP TABLE IF EXISTS teachers;

CREATE TABLE teachers(
    teacher_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    subject VARCHAR(100),
    date_of_birth DATE
);